version: '3.1'
services:
  fe:
    ports:
      - '8082:5173'
    image: 'binhotvn/diseye_fe:latest'
    restart: always
    env_file:
      - ./penv/.env
  be:
    ports:
      - '8081:3002'
    image: 'binhotvn/diseye_core_api:latest'
    restart: always
    volumes:
      - ./public:/app/public
    env_file:
      - ./penv/.env
